import Link from 'next/link';
import {
  Apple, ArrowRight, Camera, Check, CirclePlus, Play, Smartphone, Sparkles, Store, WandSparkles,
} from 'lucide-react';
import { Footer, Header, MobileDock } from './components';
import { PaymentMethods } from './payment-methods';
import { SectionTransitions } from './experience';

const categories = [
  { name: 'Fashion', note: 'Sudah tayang dari seller fashion', image: '/collection-fashion-v1.jpg', size: 'lg:col-span-2 lg:row-span-2' },
  { name: 'HP & gadget', note: 'Pilihan dari seller gadget', image: '/collection-gadget-v1.jpg', size: 'lg:col-span-2' },
  { name: 'Beauty', note: 'Listing seller beauty', image: '/collection-beauty-v1.jpg', size: 'lg:col-span-1' },
  { name: 'Rumah', note: 'Koleksi seller home living', image: '/collection-home-v1.jpg', size: 'lg:col-span-1' },
];

const products = [
  { name: 'Vivo V11 Pro 6/64', price: 'Rp950.000', old: 'Rp1.050.000', badge: 'Hemat 10%', position: '0% 0%' },
  { name: 'GM Shoes Flat Sandal', price: 'Rp70.000', badge: 'Produk lokal', position: '50% 0%' },
  { name: 'Kopi Gayo Arabika 250 gr', price: 'Rp95.000', old: 'Rp110.000', badge: 'Hemat 14%', position: '100% 0%' },
  { name: 'Arunika Work Tote', price: 'Rp749.000', badge: 'Seller pilihan', position: '0% 100%' },
  { name: 'Keramik Mug Handmade', price: 'Rp180.000', badge: 'Produk lokal', position: '50% 100%' },
  { name: 'Aluna Linen Dress', price: 'Rp385.000', badge: 'Baru masuk', position: '100% 100%' },
];

const sellerTools = [
  ['Website toko siap pakai', 'Punya website jualan sendiri yang langsung bisa dibagikan.', 'Toko online siap menerima pembeli.'],
  ['Snap · List · Sell', 'Foto barang, isi harga, lalu NEMU bantu merapikan listing.', 'Produk bisa tayang tanpa ribet nulis dari nol.'],
  ['AI foto dan konten', 'Rapikan foto produk dan ubah menjadi bahan Reels atau TikTok.', 'Konten jualan lebih menarik dan rutin.'],
  ['Iklan Google, Meta, dan TikTok', 'Jalankan iklan dari channel yang paling cocok untuk produkmu.', 'Kamu bisa lihat channel mana yang paling cuan.'],
  ['SEO dan AI search', 'Susun informasi toko serta produk agar mudah dipahami mesin pencari.', 'Lebih mudah ditemukan di Google dan pencarian AI.'],
  ['Pembayaran DOKU & 30+ kurir', 'Buyer bisa bayar online lewat DOKU, lalu seller memilih layanan pengiriman dari 30+ kurir.', 'Pembayaran dan pengiriman tertata dalam satu alur.'],
];

const faq = [
  ['NEMU itu sebenarnya apa?', 'NEMU adalah marketplace untuk buyer sekaligus channel jualan lengkap untuk seller. Buyer bisa mencari barang, sementara seller mendapatkan website toko dan alat bantu untuk mengelola serta mengembangkan penjualan.'],
  ['Kalau nggak tahu nama barangnya gimana?', 'Masuk ke Mode AI, lalu ceritakan kebutuhan, budget, warna, ukuran, atau barangnya mau dipakai untuk apa.'],
  ['Buka toko di NEMU bayar berapa?', 'Mulai gratis sampai pecah telur. Detail paket lanjutannya dibahas saat onboarding supaya sesuai kebutuhan tokomu.'],
  ['Apa saja yang didapat seller?', 'Website siap pakai, Snap List Sell, AI foto dan konten, iklan lintas platform, SEO, optimasi pencarian AI, pembayaran DOKU, 30+ kurir, dan data penjualan.'],
];

const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    { '@type': ['Organization', 'OnlineStore'], '@id': 'https://nemu-ai-redesign.openclawid6.chatgpt.site/#organization', name: 'NEMU AI', url: 'https://nemu-ai-redesign.openclawid6.chatgpt.site/', logo: 'https://nemu-ai-redesign.openclawid6.chatgpt.site/favicon.svg', description: 'Marketplace Indonesia dan website jualan berbasis AI untuk buyer dan seller.', areaServed: 'Indonesia', sameAs: ['https://nemu-ai.com/', 'https://shop.nemu-ai.com/'] },
    { '@type': 'WebSite', '@id': 'https://nemu-ai-redesign.openclawid6.chatgpt.site/#website', url: 'https://nemu-ai-redesign.openclawid6.chatgpt.site/', name: 'NEMU AI', publisher: { '@id': 'https://nemu-ai-redesign.openclawid6.chatgpt.site/#organization' }, inLanguage: 'id-ID', potentialAction: { '@type': 'SearchAction', target: 'https://nemu-ai-redesign.openclawid6.chatgpt.site/shop?q={search_term_string}', 'query-input': 'required name=search_term_string' } },
    { '@type': 'Service', name: 'Website dan alat jualan NEMU untuk seller', provider: { '@id': 'https://nemu-ai-redesign.openclawid6.chatgpt.site/#organization' }, areaServed: 'Indonesia', audience: { '@type': 'BusinessAudience', audienceType: 'Seller, UMKM, dan brand lokal' }, description: 'Website toko siap pakai dengan Snap List Sell, AI foto dan konten, iklan Google Meta TikTok, SEO, optimasi pencarian AI, pembayaran DOKU, dan 30+ pilihan kurir.' },
    { '@type': 'FAQPage', mainEntity: faq.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) },
  ],
};

export default function Home() {
  return <main className="home-page overflow-hidden bg-[#fbfbfc] text-[#0b0b0e]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <Header />
    <MobileDock />
    <SectionTransitions variant="cinematic" />

    <section className="relative isolate overflow-hidden border-b border-[#ececef] bg-[#f4f0ff] px-4 sm:px-6">
      <span className="absolute -right-32 top-16 size-[580px] rounded-full bg-[#e7dfff]"/>
      <div className="relative mx-auto grid min-h-[690px] max-w-[1240px] lg:grid-cols-[1.03fr_.97fr]">
        <div className="relative z-20 flex flex-col justify-center py-14 lg:py-20">
          <p className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.14em] text-[#704bfd]"><Sparkles size={14}/> Website toko + AI marketing buat seller</p>
          <h1 className="mt-5 max-w-[720px] font-[var(--font-display)] text-5xl font-black leading-[1.02] tracking-[-.06em] sm:text-7xl sm:leading-[.98] lg:text-[76px]">Buka toko.<br/>Promosi jalan.<br/><span className="text-[#704bfd]">NEMU bantu.</span></h1>
          <p className="mt-6 max-w-[620px] text-base font-medium leading-8 text-[#5a5a66]">Mulai gratis sampai pecah telur. Kamu dapat website siap pakai, Snap · List · Sell, AI buat foto dan konten, iklan Google–Meta–TikTok, pembayaran DOKU, dan 30+ pilihan kurir.</p>
          <div className="mt-8 flex flex-wrap gap-3"><a className="inline-flex items-center gap-3 rounded-full bg-[#704bfd] px-6 py-4 text-[10px] font-black text-white shadow-[0_12px_28px_rgba(84,54,190,.24)] transition hover:-translate-y-1" href="#jadwal-onboarding"><Store size={17}/> Buka toko gratis</a><a className="inline-flex items-center gap-3 rounded-full border border-[#dcdce0] bg-white px-6 py-4 text-[10px] font-black text-[#704bfd] transition hover:-translate-y-1" href="#snap-list-sell"><Sparkles size={17}/> Lihat cara kerjanya</a><a className="inline-flex items-center gap-3 rounded-full border border-[#cfc3ff] bg-[#ede8ff] px-6 py-4 text-[10px] font-black text-[#704bfd] transition hover:-translate-y-1 hover:bg-white" href="#download-app"><Smartphone size={17}/> Download aplikasi</a></div>
          <div className="mt-10 grid max-w-[680px] gap-5 border-t border-[#dcdce0] pt-6 sm:grid-cols-2"><div><p className="text-[8px] font-black uppercase tracking-[.14em] text-[#704bfd]">Mulai tanpa takut rugi</p><p className="mt-2 text-[10px] leading-6 text-[#5a5a66]">Rp0 sampai penjualan pertama. Lanjut hanya saat tokomu sudah pecah telur.</p></div><div className="border-[#dcdce0] sm:border-l sm:pl-6"><p className="text-[8px] font-black uppercase tracking-[.14em] text-[#704bfd]">Nggak perlu rakit sendiri</p><p className="mt-2 text-[10px] leading-6 text-[#5a5a66]">Website, konten, iklan, pembayaran, dan kiriman sudah saling nyambung.</p></div></div>
        </div>
        <div className="relative min-h-[560px] self-end sm:min-h-[600px] lg:min-h-full"><img className="absolute bottom-0 left-[30%] z-10 h-[68%] w-auto max-w-none -translate-x-1/2 object-contain drop-shadow-[0_28px_28px_rgba(71,47,128,.20)] sm:left-[34%] sm:h-[72%] lg:left-[42%] lg:h-[92%]" src="/model-hero-buyer-v2.png" alt="Perempuan Indonesia menggunakan NEMU untuk belanja dan jualan"/><div className="absolute right-3 top-3 z-30 w-[58%] max-w-[210px] rounded-[22px] bg-white p-4 shadow-[0_18px_40px_rgba(54,36,112,.16)] sm:right-6 sm:top-8 sm:max-w-[220px] lg:right-[2%] lg:top-[14%] lg:max-w-[250px]"><span className="absolute -left-2 top-16 hidden size-5 rotate-45 bg-white lg:block"/><p className="text-[7px] font-black uppercase tracking-[.14em] text-[#704bfd]">Seller yang sudah mulai</p><p className="mt-2 text-[12px] font-black leading-[1.45] tracking-[-.02em] text-[#1a1a1f]">“100+ seller sudah gabung. Sekarang giliran tokomu.”</p><div className="mt-3 grid grid-cols-4 items-center gap-2 border-t border-[#ececef] pt-3">{[['https://nemu-ai.com/_next/static/media/fdr-logo.d19a7a83.svg','FDR'],['https://nemu-ai.com/_next/static/media/arei-outdoor-gear-logo.474cad27.svg','AREI'],['https://nemu-ai.com/_next/static/media/kemfood-logo.61ab1b2c.svg','Kemfood'],['https://nemu-ai.com/_next/static/media/tracker-logo.ef0c9116.svg','Tracker']].map(([src,name])=><img className="h-4 w-full object-contain brightness-0 opacity-55" src={src} alt={`Logo seller ${name}`} key={name}/>)}</div></div></div>
      </div>
    </section>

    <section className="bg-white px-4 py-20 sm:px-6 lg:py-28" aria-labelledby="seller-tools-heading"><div className="mx-auto max-w-[1240px]"><div className="grid gap-6 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#704bfd]">Yang seller dapat</p><h2 id="seller-tools-heading" className="mt-3 text-4xl font-black leading-[.98] tracking-[-.05em] sm:text-5xl">Jualan di NEMU dapat apa aja?</h2></div><p className="max-w-2xl text-sm leading-7 text-[#6b6b75] lg:ml-auto">Dari website toko dan promosi sampai pembayaran DOKU serta 30+ pilihan kurir, semuanya sudah disiapkan supaya kamu bisa fokus jualan.</p></div><div className="mt-10 overflow-x-auto rounded-[26px] border border-[#dcdce0]"><table className="w-full min-w-[860px] border-collapse text-left"><caption className="sr-only">Daftar fitur seller NEMU, kegunaan, dan hasilnya</caption><thead className="bg-[#704bfd] text-white"><tr><th className="w-[28%] px-6 py-5 text-[9px] font-black uppercase tracking-[.13em]" scope="col">Fitur seller NEMU</th><th className="w-[38%] px-6 py-5 text-[9px] font-black uppercase tracking-[.13em]" scope="col">Yang NEMU bantu</th><th className="px-6 py-5 text-[9px] font-black uppercase tracking-[.13em]" scope="col">Hasil buat tokomu</th></tr></thead><tbody>{sellerTools.map(([title,help,result],index)=><tr className={index%2===0?'bg-white':'bg-[#f8f6ff]'} key={title}><th className="border-t border-[#e4e0eb] px-6 py-6 align-top text-base font-black tracking-[-.025em]" scope="row"><span className="mr-3 text-[9px] text-[#704bfd]">0{index+1}</span>{title}</th><td className="border-t border-[#e4e0eb] px-6 py-6 align-top text-[10px] leading-6 text-[#5a5a66]">{help}</td><td className="border-t border-[#e4e0eb] px-6 py-6 align-top text-[10px] font-bold leading-6 text-[#3a3a42]">{result}</td></tr>)}</tbody></table></div></div></section>

    <section className="relative overflow-hidden bg-[#704bfd] px-4 text-white sm:px-6"><span className="absolute -left-36 bottom-0 size-[390px] rounded-full border-[62px] border-white/10"/><div className="relative mx-auto grid min-h-[520px] max-w-[1240px] lg:grid-cols-[1.03fr_.97fr]"><div className="relative z-10 flex flex-col justify-center py-12"><p className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.15em] text-[#e7dfff]"><Store size={15}/> Harga seller NEMU</p><h2 className="mt-4 max-w-[560px] text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-5xl lg:text-[52px]">Mulai gratis.<br/><span className="text-[#e7dfff]">Lanjut setelah laku.</span></h2><p className="mt-5 max-w-[540px] text-sm font-medium leading-7 text-white/85">Mulai tanpa biaya sampai pecah telur. Website toko, AI foto dan konten, iklan, pembayaran DOKU, serta 30+ kurir sudah siap buat tokomu.</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-[9px] font-black text-white"><span>AI foto & konten</span><span>Google · Meta · TikTok</span><span>DOKU · 30+ kurir</span></div><div className="mt-6 flex flex-wrap items-center gap-4"><a className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-4 text-[10px] font-black text-[#704bfd] shadow-[0_8px_20px_rgba(20,20,30,.12)]" href="#jadwal-onboarding">Buka toko gratis <ArrowRight size={15}/></a><a className="inline-flex items-center gap-2 rounded-full border border-white/30 px-5 py-3 text-[9px] font-black text-white" href="#download-app"><Smartphone size={15}/> Download aplikasi</a></div></div><div className="relative min-h-[430px] self-end sm:min-h-[480px] lg:min-h-[520px]"><img className="absolute bottom-0 left-[42%] h-[94%] w-auto max-w-none -translate-x-1/2 object-contain drop-shadow-[0_24px_24px_rgba(42,24,96,.24)] sm:left-[38%] sm:h-[100%] lg:left-[32%] lg:h-[88%]" src="/model-seller-coral-v2.png" alt="Seller perempuan mengelola website toko NEMU"/><div className="absolute right-2 top-12 z-20 max-w-[230px] rounded-[22px] bg-white p-5 text-[#17131f] shadow-[0_18px_42px_rgba(32,20,78,.22)] sm:right-6 sm:top-16"><span className="absolute -left-3 top-12 size-6 rotate-45 bg-white"/><div className="relative"><p className="text-[7px] font-black uppercase tracking-[.14em] text-[#704bfd]">Harga seller NEMU</p><p className="mt-2 text-base font-black leading-5">Mulai gratis sampai pecah telur.</p><p className="mt-2 text-[9px] font-bold text-[#6b6b75]">Lanjut Rp199 ribu/bulan.</p></div></div></div></div></section>

    <PaymentMethods />

    <section className="px-4 py-20 sm:px-6 lg:py-28" aria-labelledby="buyer-heading">
      <div className="mx-auto max-w-[1240px]"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#704bfd]">Sudah tayang di NEMU</p><h2 id="buyer-heading" className="mt-3 text-4xl font-black leading-[.98] tracking-[-.05em] sm:text-5xl">Seller NEMU jualan apa aja?</h2></div><p className="max-w-xl text-sm leading-7 text-[#6b6b75] lg:ml-auto">Lihat kategori produk yang sudah ditayangkan seller di NEMU Marketplace. Dari fashion, gadget, beauty, sampai kebutuhan rumah.</p></div>
        <div className="mt-10 grid gap-4 lg:grid-cols-4 lg:grid-rows-[230px_230px]">{categories.map(category=><Link className={`group relative min-h-[230px] overflow-hidden ${category.size}`} href="/shop" key={category.name}><span className="absolute inset-0 bg-cover bg-center transition duration-700 group-hover:scale-105" style={{backgroundImage:`url('${category.image}')`}}/><span className="absolute inset-0 bg-gradient-to-t from-[#1a1a1f]/80 via-transparent to-transparent"/><div className="absolute inset-x-6 bottom-6 text-white"><p className="text-[8px] font-black uppercase tracking-[.12em] text-white/70">{category.note}</p><h3 className="mt-1 text-2xl font-black">{category.name}</h3></div><span className="absolute bottom-6 right-6 grid size-10 place-items-center rounded-full bg-white text-[#704bfd]"><ArrowRight size={16}/></span></Link>)}</div>
      </div>
    </section>

    <section className="border-y border-[#ececef] bg-white px-4 py-20 sm:px-6 lg:py-24" id="produk" aria-labelledby="trending-heading"><div className="mx-auto max-w-[1240px]"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#704bfd]">Listing seller NEMU</p><h2 id="trending-heading" className="mt-2 text-4xl font-black tracking-[-.055em] sm:text-5xl">Produk seller yang sudah tayang.</h2><p className="mt-3 max-w-xl text-sm leading-7 text-[#6b6b75]">Intip barang yang sudah dilisting seller di NEMU Marketplace.</p></div><Link className="inline-flex w-fit items-center gap-2 text-[9px] font-black text-[#704bfd]" href="/shop">Lihat semua produk <ArrowRight size={14}/></Link></div>
      <div className="mt-10 grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-3 lg:grid-cols-6">{products.map(product=><article className="group" key={product.name}><div className="relative aspect-[.86] overflow-hidden bg-[#f3f3f7]"><span className="absolute inset-0 bg-cover bg-center bg-no-repeat transition duration-500 group-hover:scale-105" role="img" aria-label={product.name} style={{backgroundImage:"url('/product-sprite-a-v1.png')",backgroundSize:'300% 200%',backgroundPosition:product.position}}/><span className="absolute left-3 top-3 rounded-full bg-[#704bfd] px-3 py-1.5 text-[7px] font-black text-white">{product.badge}</span></div><div className="pt-4"><h3 className="line-clamp-2 min-h-9 text-[10px] font-black leading-4">{product.name}</h3><strong className="mt-2 block text-base">{product.price}</strong>{product.old&&<small className="mt-1 block text-[8px] text-[#84848f] line-through">{product.old}</small>}<Link className="mt-3 inline-flex items-center gap-1 text-[8px] font-black text-[#704bfd]" href="/shop">Buka produk <ArrowRight size={11}/></Link></div></article>)}</div></div></section>



    <section className="bg-white px-4 py-16 sm:px-6 lg:py-24" id="snap-list-sell" aria-labelledby="snap-list-sell-heading">
      <div className="mx-auto max-w-[1240px]">
        <div className="grid gap-5 lg:grid-cols-[.72fr_1.28fr] lg:items-end">
          <div><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#704bfd]">Snap · List · Sell</p><h2 id="snap-list-sell-heading" className="mt-3 text-4xl font-black leading-[.98] tracking-[-.05em] sm:text-5xl">Jepret barangnya.<br/>NEMU yang beresin.</h2></div>
          <p className="max-w-2xl text-sm leading-7 text-[#6b6b75] lg:ml-auto">Kamu tentuin harga. Nama produk, deskripsi, sampai kategori dibantu NEMU. Tinggal cek sebentar, langsung tayang.</p>
        </div>
        <div className="mt-9 overflow-hidden rounded-[32px] border border-[#ded8e8] bg-[#f4f0ff] shadow-[0_22px_65px_rgba(66,44,125,.10)]">
          <div className="grid lg:grid-cols-[.94fr_1.06fr]">
            <div className="relative min-h-[360px] overflow-hidden sm:min-h-[460px]">
              <img className="absolute inset-0 size-full object-cover" src="/seller-content-woman-v1.jpg" alt="Seller memotret produk untuk dibuatkan listing oleh NEMU"/>
              <span className="absolute inset-0 bg-gradient-to-t from-[#24183d]/75 via-transparent to-transparent"/>
              <div className="absolute inset-x-5 bottom-5 rounded-[22px] border border-white/25 bg-white/90 p-4 text-[#17131f] shadow-xl backdrop-blur sm:inset-x-7 sm:bottom-7 sm:p-5">
                <span className="flex items-center gap-2 text-[8px] font-black uppercase tracking-[.13em] text-[#704bfd]"><Camera size={14}/> Mulai dari foto</span>
                <p className="mt-2 text-lg font-black tracking-[-.035em]">Jepret. Udah.</p>
                <p className="mt-1 text-[9px] leading-5 text-[#6b6b75]">Pakai kamera HP juga bisa. Nggak perlu jago foto produk.</p>
              </div>
            </div>
            <div className="flex flex-col justify-between p-5 sm:p-8 lg:p-10">
              <div className="rounded-[26px] border border-[#dcd4ef] bg-white p-4 shadow-[0_16px_36px_rgba(54,36,112,.10)] sm:p-5">
                <div className="flex items-center justify-between gap-4 border-b border-[#ece8f3] pb-4"><span className="flex items-center gap-2 text-[8px] font-black uppercase tracking-[.13em] text-[#704bfd]"><WandSparkles size={14}/> Dibikinin NEMU</span><span className="rounded-full bg-[#e9ffd1] px-3 py-1.5 text-[7px] font-black text-[#356500]">Udah rapi</span></div>
                <div className="mt-4 grid grid-cols-[92px_1fr] gap-4 sm:grid-cols-[140px_1fr]">
                  <div className="aspect-square overflow-hidden rounded-[18px] bg-[#eeeaf5]"><span className="block size-full bg-cover" style={{backgroundImage:"url('/collection-beauty-v1.jpg')",backgroundPosition:'42% center'}}/></div>
                  <div className="min-w-0 py-1"><p className="text-[7px] font-black uppercase tracking-[.12em] text-[#8a7f96]">Siap masuk tokomu</p><h3 className="mt-1 text-sm font-black leading-5 sm:text-lg">Glow Drop Face Serum 20 ml</h3><p className="mt-2 line-clamp-2 text-[8px] leading-4 text-[#6b6b75]">Serum wajah ringan buat pagi dan malam. Cepat meresap dan nggak lengket.</p><strong className="mt-3 block text-lg text-[#704bfd]">Rp89.000</strong></div>
                </div>
              </div>
              <div className="mt-5 grid gap-3 sm:grid-cols-3">
                {[['01','Jepret','Foto pakai HP'],['02','Dibikinin','Nama sampai kategori'],['03','Tinggal tayang','Harga kamu yang atur']].map(([number,title,copy],index)=><div className={`rounded-[20px] border p-4 ${index===2?'border-[#704bfd] bg-[#704bfd] text-white':'border-[#dcd4ef] bg-white'}`} key={number}><span className={`grid size-7 place-items-center rounded-full text-[8px] font-black ${index===2?'bg-white text-[#704bfd]':'bg-[#f0ebff] text-[#704bfd]'}`}>{index===2?<Check size={13}/>:number}</span><b className="mt-3 block text-[10px]">{title}</b><p className={`mt-1 text-[8px] leading-4 ${index===2?'text-white/75':'text-[#6b6b75]'}`}>{copy}</p></div>)}</div>
              <a className="mt-6 inline-flex w-fit items-center gap-2 rounded-full bg-[#17131f] px-6 py-4 text-[10px] font-black text-white transition hover:-translate-y-1 hover:bg-[#704bfd]" href="#jadwal-onboarding">Coba jualan gratis <ArrowRight size={15}/></a>
            </div>
          </div>
        </div>
      </div>
    </section>



    <section className="relative overflow-hidden border-y border-[#ececef] bg-[#f4f0ff] px-4 py-14 sm:px-6 lg:py-16"><span className="absolute -right-28 -top-28 size-[340px] rounded-full border-[56px] border-white/60"/><div className="relative mx-auto grid max-w-[1240px] gap-8 lg:grid-cols-[.68fr_1.32fr] lg:items-center"><div className="relative z-20"><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#704bfd]">Cari pakai Mode AI</p><h2 className="mt-3 text-4xl font-black leading-[.98] tracking-[-.05em] sm:text-5xl">Cukup bilang<br/>maunya apa.</h2><p className="mt-4 max-w-md text-sm leading-7 text-[#6b6b75]">Tulis kebutuhan, budget, atau gaya yang kamu mau. NEMU bantu cariin pilihan yang paling pas.</p><Link className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#704bfd] px-6 py-4 text-[10px] font-black text-white" href="/ai-mode">Cari pakai Mode AI <ArrowRight size={15}/></Link></div><div className="relative min-h-[440px]"><img className="absolute bottom-0 left-[2%] h-[92%] w-auto max-w-none object-contain" src="/ai-shopping-visual-v1.png" alt="Perempuan mencari produk dengan bantuan Mode AI NEMU"/><div className="absolute right-0 top-6 z-20 max-w-[270px] rounded-[20px] bg-white p-4 shadow-[0_14px_30px_rgba(61,39,130,.12)]"><p className="text-[7px] font-black uppercase tracking-[.13em] text-[#704bfd]">Kamu ketik</p><p className="mt-2 text-[11px] font-black leading-5">“Sepatu putih buat kuliah. Empuk. Budget 300 ribuan.”</p></div><div className="absolute bottom-4 right-0 z-20 max-w-[290px] rounded-[20px] bg-[#704bfd] p-4 text-white shadow-[0_14px_30px_rgba(61,39,130,.18)]"><p className="text-[7px] font-black uppercase tracking-[.13em] text-[#e7dfff]">NEMU cariin</p><p className="mt-2 text-[10px] font-black leading-5">Sepatu putih · empuk · gampang dibersihkan · maksimal Rp300 ribu</p></div></div></div></section>



    <section className="bg-[#704bfd] py-16 text-white" id="download-app" aria-labelledby="download-heading"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#e7dfff]">NEMU di genggaman</p><h2 id="download-heading" className="mt-3 text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-5xl">Belanja dan urus toko dari HP.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/75">Cari barang, cek pesanan, atau lanjut jualan kapan saja lewat aplikasi NEMU.</p></div><div className="flex flex-wrap gap-3"><a className="inline-flex min-w-[190px] items-center gap-3 rounded-2xl bg-[#1a1a1f] px-5 py-3 text-white shadow-[0_12px_24px_rgba(32,20,78,.22)] transition hover:-translate-y-1" href="https://apps.apple.com/id/app/nemu-ai-marketplace/id6789514376"><Apple className="shrink-0 text-white" size={28}/><span className="text-white"><small className="block text-[7px] font-bold text-white/65">Download di</small><b className="block text-sm text-white">App Store</b></span></a><a className="inline-flex min-w-[190px] items-center gap-3 rounded-2xl bg-[#1a1a1f] px-5 py-3 text-white shadow-[0_12px_24px_rgba(32,20,78,.22)] transition hover:-translate-y-1" href="https://play.google.com/store/apps/details?id=com.nemump.nemumobile&pcampaignid=web_share"><Play className="shrink-0 fill-white text-white" size={26}/><span className="text-white"><small className="block text-[7px] font-bold text-white/65">Download di</small><b className="block text-sm text-white">Google Play</b></span></a></div></div></section>

    <section className="bg-white px-4 py-20 sm:px-6 lg:py-28" aria-labelledby="faq-heading"><div className="mx-auto grid max-w-[1240px] overflow-hidden rounded-[34px] border border-[#dcdce0] lg:grid-cols-[.72fr_1.28fr]"><div className="relative overflow-hidden bg-[#704bfd] p-8 text-white sm:p-12"><span className="absolute -bottom-28 -left-24 size-[330px] rounded-full border-[58px] border-white/10"/><div className="relative"><span className="grid size-14 place-items-center rounded-full bg-white text-[#704bfd]"><Sparkles size={24}/></span><p className="mt-10 text-[9px] font-black uppercase tracking-[.15em] text-[#e7dfff]">Yang sering ditanyain</p><h2 id="faq-heading" className="mt-3 text-4xl font-black leading-[.98] tracking-[-.05em] sm:text-5xl">Masih ada yang bikin ragu?</h2><p className="mt-5 max-w-sm text-sm leading-7 text-white/75">Cek jawaban singkatnya. Kalau barang yang dicari belum kebayang, langsung ceritakan ke Mode AI.</p><Link className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-[9px] font-black" style={{color:'#704bfd'}} href="/ai-mode"><span style={{color:'#704bfd'}}>Tanya Mode AI</span><ArrowRight style={{color:'#704bfd'}} size={14}/></Link></div></div><div className="bg-[#fbfbfc] p-6 sm:p-10">{faq.map(([question,answer],index)=><details className="faq-item group mb-3 rounded-[20px] border border-[#e4e0eb] bg-white px-5 open:border-[#b9a8ff] open:shadow-[0_10px_24px_rgba(61,39,130,.08)]" key={question} open={index===0}><summary className="flex cursor-pointer list-none items-center justify-between gap-5 py-5 text-[11px] font-black"><span className="flex items-center gap-3"><b className="text-[8px] text-[#704bfd]">0{index+1}</b>{question}</span><CirclePlus className="shrink-0 text-[#704bfd] transition group-open:rotate-45" size={20}/></summary><p className="border-t border-[#ececef] pb-5 pt-4 text-[10px] leading-6 text-[#6b6b75]">{answer}</p></details>)}</div></div></section>
    <Footer/>
  </main>;
}
