import Link from 'next/link';
import {
  Apple, ArrowRight, BadgeCheck, Check, CirclePlus, CreditCard, Play, Search,
  ShoppingBag, Sparkles, Store, Truck,
} from 'lucide-react';
import { Footer, Header, MobileDock } from './components';
import { PaymentMethods } from './payment-methods';

const categories = [
  { name: 'Fashion', note: 'Buat ngampus sampai kondangan', image: '/collection-fashion-v1.jpg', size: 'lg:col-span-2 lg:row-span-2' },
  { name: 'HP & gadget', note: 'Yang kepakai tiap hari', image: '/collection-gadget-v1.jpg', size: 'lg:col-span-2' },
  { name: 'Beauty', note: 'Skincare dan makeup pilihan', image: '/collection-beauty-v1.jpg', size: 'lg:col-span-1' },
  { name: 'Rumah', note: 'Biar makin betah', image: '/collection-home-v1.jpg', size: 'lg:col-span-1' },
];

const products = [
  { name: 'Vivo V11 Pro 6/64', price: 'Rp950.000', old: 'Rp1.050.000', badge: 'Hemat 10%', position: '0% 0%' },
  { name: 'GM Shoes Flat Sandal', price: 'Rp70.000', badge: 'Produk lokal', position: '50% 0%' },
  { name: 'Kopi Gayo Arabika 250 gr', price: 'Rp95.000', old: 'Rp110.000', badge: 'Hemat 14%', position: '100% 0%' },
  { name: 'Arunika Work Tote', price: 'Rp749.000', badge: 'Seller pilihan', position: '0% 100%' },
  { name: 'Keramik Mug Handmade', price: 'Rp180.000', badge: 'Produk lokal', position: '50% 100%' },
  { name: 'Aluna Linen Dress', price: 'Rp385.000', badge: 'Baru masuk', position: '100% 100%' },
];

const sellerTools = [
  ['01', 'Website toko siap pakai', 'Punya channel jualan sendiri yang langsung bisa kamu bagikan.'],
  ['02', 'Snap · List · Sell', 'Foto barang, isi harga, lalu NEMU bantu merapikan listing sebelum tayang.'],
  ['03', 'AI foto dan konten', 'Bikin foto jualan lebih menarik dan ubah jadi bahan Reels atau TikTok.'],
  ['04', 'Iklan Google, Meta, dan TikTok', 'Jalankan iklan dan lihat channel mana yang paling menghasilkan.'],
  ['05', 'SEO dan AI search', 'Bantu toko serta produkmu lebih mudah ditemukan di Google dan pencarian AI.'],
  ['06', 'DOKU, 30+ kurir, dan data jualan', 'Pembayaran, pengiriman, omzet, dan untung tetap dalam satu alur.'],
];

const faq = [
  ['NEMU itu sebenarnya apa?', 'NEMU adalah marketplace untuk buyer sekaligus channel jualan lengkap untuk seller. Buyer bisa mencari barang, sementara seller mendapatkan website toko dan alat bantu untuk mengelola serta mengembangkan penjualan.'],
  ['Kalau nggak tahu nama barangnya gimana?', 'Masuk ke Mode AI, lalu ceritakan kebutuhan, budget, warna, ukuran, atau barangnya mau dipakai untuk apa.'],
  ['Buka toko di NEMU bayar berapa?', 'Gratis sampai pecah telur. Setelah penjualan pertama, lanjut Rp199 ribu per bulan.'],
  ['Apa saja yang didapat seller?', 'Website siap pakai, Snap List Sell, AI foto dan konten, iklan lintas platform, SEO, optimasi pencarian AI, pembayaran DOKU, 30+ kurir, dan data penjualan.'],
];

const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    { '@type': 'Organization', name: 'NEMU AI', url: 'https://nemu-ai-redesign.openclawid6.chatgpt.site/', logo: 'https://nemu-ai-redesign.openclawid6.chatgpt.site/favicon.svg' },
    { '@type': 'WebSite', url: 'https://nemu-ai-redesign.openclawid6.chatgpt.site/', name: 'NEMU AI', inLanguage: 'id-ID', potentialAction: { '@type': 'SearchAction', target: 'https://nemu-ai-redesign.openclawid6.chatgpt.site/shop?q={search_term_string}', 'query-input': 'required name=search_term_string' } },
    { '@type': 'FAQPage', mainEntity: faq.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) },
  ],
};

export default function Home() {
  return <main className="home-page overflow-hidden bg-[#fbfbfc] text-[#0b0b0e]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <Header />
    <MobileDock />

    <section className="relative isolate overflow-hidden border-b border-[#ececef] bg-[#f4f0ff] px-4 sm:px-6">
      <span className="absolute -right-32 top-16 size-[580px] rounded-full bg-[#e7dfff]"/>
      <span className="absolute right-[7%] top-[16%] size-[380px] rounded-full border-[72px] border-white/55"/>
      <div className="relative mx-auto grid min-h-[690px] max-w-[1240px] lg:grid-cols-[1.03fr_.97fr]">
        <div className="relative z-20 flex flex-col justify-center py-14 lg:py-20">
          <p className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.14em] text-[#704bfd]"><Sparkles size={14}/> Marketplace + website jualan berbasis AI</p>
          <h1 className="mt-5 max-w-[720px] font-[var(--font-display)] text-5xl font-black leading-[1.02] tracking-[-.06em] sm:text-7xl sm:leading-[.98] lg:text-[76px]">Cari barang.<br/>Mulai jualan.<br/><span className="text-[#704bfd]">NEMU bantu.</span></h1>
          <p className="mt-6 max-w-[620px] text-base font-medium leading-8 text-[#5a5a66]">Buyer tinggal bilang apa yang dicari. Seller langsung punya website, dibantu AI bikin konten dan iklan, lalu bisa lihat channel mana yang paling cuan.</p>
          <div className="mt-8 flex flex-wrap gap-3"><Link className="inline-flex items-center gap-3 rounded-full bg-[#704bfd] px-6 py-4 text-[10px] font-black text-white shadow-[0_8px_20px_rgba(112,75,253,.26)] transition hover:-translate-y-1 hover:bg-[#5a36e8]" href="/shop"><ShoppingBag size={17}/> Mulai belanja <ArrowRight size={15}/></Link><a className="inline-flex items-center gap-3 rounded-full border border-[#dcdce0] bg-white px-6 py-4 text-[10px] font-black text-[#704bfd] transition hover:-translate-y-1" href="https://seller.nemu-ai.com/register"><Store size={17}/> Buka toko gratis</a></div>
          <div className="mt-10 grid max-w-[650px] gap-5 border-t border-[#dcdce0] pt-6 sm:grid-cols-2"><div><p className="text-[8px] font-black uppercase tracking-[.14em] text-[#704bfd]">Buat buyer</p><p className="mt-2 text-[10px] leading-6 text-[#5a5a66]">Cari barang baru, preloved, dan produk lokal pakai kata biasa atau Mode AI.</p></div><div className="border-[#dcdce0] sm:border-l sm:pl-6"><p className="text-[8px] font-black uppercase tracking-[.14em] text-[#704bfd]">Buat seller</p><p className="mt-2 text-[10px] leading-6 text-[#5a5a66]">Website, AI marketing, iklan, pembayaran, kurir, dan data jualan dalam satu tempat.</p></div></div>
        </div>
        <div className="relative min-h-[520px] self-end lg:min-h-full"><img className="absolute bottom-0 left-[56%] z-10 h-[76%] w-auto max-w-none -translate-x-1/2 object-contain drop-shadow-[0_28px_28px_rgba(71,47,128,.20)] sm:h-[82%] lg:h-[86%]" src="/model-hero-buyer-v2.png" alt="Perempuan Indonesia menggunakan NEMU untuk belanja dan jualan"/><div className="absolute left-1/2 top-4 z-30 w-[90%] max-w-[290px] -translate-x-1/2 rounded-[26px] bg-white p-5 shadow-[0_18px_40px_rgba(54,36,112,.16)] lg:left-0 lg:top-[14%] lg:translate-x-0"><span className="absolute -right-3 top-14 hidden size-6 rotate-45 bg-white lg:block"/><p className="text-[8px] font-black uppercase tracking-[.14em] text-[#704bfd]">Kata yang belanja di NEMU</p><p className="mt-2 text-[14px] font-black leading-5 tracking-[-.02em] text-[#1a1a1f]">“Udah ada 100+ seller. Tinggal pilih yang aku suka.”</p><div className="mt-4 grid grid-cols-4 items-center gap-3 border-t border-[#ececef] pt-4">{[['https://nemu-ai.com/_next/static/media/fdr-logo.d19a7a83.svg','FDR'],['https://nemu-ai.com/_next/static/media/arei-outdoor-gear-logo.474cad27.svg','AREI'],['https://nemu-ai.com/_next/static/media/kemfood-logo.61ab1b2c.svg','Kemfood'],['https://nemu-ai.com/_next/static/media/tracker-logo.ef0c9116.svg','Tracker']].map(([src,name])=><img className="h-5 w-full object-contain grayscale opacity-60" src={src} alt={`Logo seller ${name}`} key={name}/>)}</div></div></div>
      </div>
    </section>

    <section className="border-b border-[#ececef] bg-white px-4 py-5 sm:px-6" aria-label="Keunggulan NEMU"><div className="mx-auto grid max-w-[1240px] grid-cols-2 gap-5 lg:grid-cols-4">{[[Search,'Cari pakai bahasa sehari-hari'],[BadgeCheck,'Seller gampang dicek'],[CreditCard,'Bayar online lewat DOKU'],[Truck,'30+ pilihan kurir']].map(([Icon,label])=>{const I=Icon as typeof Search;return <div className="flex items-center gap-3" key={label as string}><I className="shrink-0 text-[#704bfd]" size={19}/><b className="text-[10px] leading-4 text-[#3a3a42]">{label as string}</b></div>})}</div></section>

    <section className="px-4 py-20 sm:px-6 lg:py-28" aria-labelledby="buyer-heading">
      <div className="mx-auto max-w-[1240px]"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#704bfd]">Buat yang lagi cari barang</p><h2 id="buyer-heading" className="mt-3 text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-5xl">Mulai dari yang paling kamu banget.</h2></div><p className="max-w-xl text-sm leading-7 text-[#6b6b75] lg:ml-auto">Kamu bisa cari lewat kategori seperti biasa, atau ceritakan kebutuhanmu ke Mode AI kalau belum tahu nama barangnya.</p></div>
        <div className="mt-10 grid gap-4 lg:grid-cols-4 lg:grid-rows-[230px_230px]">{categories.map(category=><Link className={`group relative min-h-[230px] overflow-hidden ${category.size}`} href="/shop" key={category.name}><span className="absolute inset-0 bg-cover bg-center transition duration-700 group-hover:scale-105" style={{backgroundImage:`url('${category.image}')`}}/><span className="absolute inset-0 bg-gradient-to-t from-[#1a1a1f]/80 via-transparent to-transparent"/><div className="absolute inset-x-6 bottom-6 text-white"><p className="text-[8px] font-black uppercase tracking-[.12em] text-white/70">{category.note}</p><h3 className="mt-1 text-2xl font-black">{category.name}</h3></div><span className="absolute bottom-6 right-6 grid size-10 place-items-center rounded-full bg-white text-[#704bfd]"><ArrowRight size={16}/></span></Link>)}</div>
      </div>
    </section>

    <section className="border-y border-[#ececef] bg-white px-4 py-20 sm:px-6 lg:py-24" id="produk" aria-labelledby="trending-heading"><div className="mx-auto max-w-[1240px]"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#704bfd]">Lagi ramai</p><h2 id="trending-heading" className="mt-2 text-4xl font-black tracking-[-.055em] sm:text-5xl">Banyak yang lagi ngincer ini.</h2></div><Link className="inline-flex w-fit items-center gap-2 text-[9px] font-black text-[#704bfd]" href="/shop">Lihat semua <ArrowRight size={14}/></Link></div>
      <div className="mt-10 grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-3 lg:grid-cols-6">{products.map(product=><article className="group" key={product.name}><div className="relative aspect-[.86] overflow-hidden bg-[#f3f3f7]"><span className="absolute inset-0 bg-cover bg-center bg-no-repeat transition duration-500 group-hover:scale-105" role="img" aria-label={product.name} style={{backgroundImage:"url('/product-sprite-a-v1.png')",backgroundSize:'300% 200%',backgroundPosition:product.position}}/><span className="absolute left-3 top-3 rounded-full bg-[#704bfd] px-3 py-1.5 text-[7px] font-black text-white">{product.badge}</span></div><div className="pt-4"><h3 className="line-clamp-2 min-h-9 text-[10px] font-black leading-4">{product.name}</h3><strong className="mt-2 block text-base">{product.price}</strong>{product.old&&<small className="mt-1 block text-[8px] text-[#84848f] line-through">{product.old}</small>}<Link className="mt-3 inline-flex items-center gap-1 text-[8px] font-black text-[#704bfd]" href="/shop">Lihat produk <ArrowRight size={11}/></Link></div></article>)}</div></div></section>

    <section className="relative overflow-hidden bg-[#704bfd] px-4 text-white sm:px-6"><span className="absolute -left-40 bottom-0 size-[480px] rounded-full border-[76px] border-white/10"/><div className="relative mx-auto grid min-h-[650px] max-w-[1240px] lg:grid-cols-[1.03fr_.97fr]"><div className="relative z-10 flex flex-col justify-center py-16"><p className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.15em] text-[#e7dfff]"><Store size={15}/> Buat seller</p><h2 className="mt-4 max-w-[660px] text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-6xl">Tambah channel jualan.<br/><span className="text-[#e7dfff]">Bukan tambah ribet.</span></h2><p className="mt-6 max-w-xl text-sm leading-7 text-white/80">Di NEMU, seller langsung punya website siap pakai. Foto produk dan konten dibantu AI, iklan bisa jalan di Google, Meta, dan TikTok, pembayaran lewat DOKU, lalu pengiriman dipilih dari 30+ kurir.</p><div className="mt-8 flex flex-wrap items-center gap-3"><a className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-4 text-[10px] font-black text-[#704bfd] shadow-[0_8px_20px_rgba(20,20,30,.12)]" href="https://seller.nemu-ai.com/register">Buka toko gratis <ArrowRight size={15}/></a><span className="text-[9px] font-black text-white/75">Gratis sampai pecah telur · lalu Rp199 ribu/bulan</span></div></div><div className="relative min-h-[560px] self-end"><img className="absolute bottom-0 left-1/2 h-[88%] w-auto max-w-none -translate-x-1/2 object-contain drop-shadow-[0_30px_28px_rgba(42,24,96,.28)]" src="/model-seller-coral-v2.png" alt="Seller perempuan mengelola website toko NEMU"/></div></div></section>

    <section className="bg-white px-4 py-20 sm:px-6 lg:py-28" aria-labelledby="seller-tools-heading"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[.7fr_1.3fr]"><div className="lg:sticky lg:top-36 lg:self-start"><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#704bfd]">Yang seller dapat</p><h2 id="seller-tools-heading" className="mt-3 text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-5xl">Nggak cuma punya toko. Kamu tahu harus ngapain.</h2><p className="mt-5 max-w-md text-sm leading-7 text-[#6b6b75]">NEMU merapikan pekerjaan harian dan menampilkan data yang paling penting. Kamu tetap yang memutuskan.</p></div><div className="border-t border-[#dcdce0]">{sellerTools.map(([number,title,copy])=><div className="grid gap-4 border-b border-[#dcdce0] py-7 sm:grid-cols-[64px_.7fr_1fr] sm:items-start" key={number}><span className="text-sm font-black text-[#704bfd]">{number}</span><h3 className="text-xl font-black tracking-[-.035em]">{title}</h3><p className="text-[10px] leading-6 text-[#6b6b75]">{copy}</p></div>)}</div></div></section>

    <section className="border-y border-[#ececef] bg-[#f4f0ff] px-4 py-20 sm:px-6 lg:py-24"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#704bfd]">Mode AI buat buyer</p><h2 className="mt-3 text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-5xl">Nggak tahu nama barangnya? Ceritain aja.</h2><p className="mt-5 max-w-md text-sm leading-7 text-[#6b6b75]">Sebut kebutuhan, budget, warna, ukuran, atau dipakai buat apa. NEMU bantu menyaring pilihan yang lebih masuk.</p><Link className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#704bfd] px-6 py-4 text-[10px] font-black text-white" href="/ai-mode">Buka Mode AI <ArrowRight size={15}/></Link></div><div className="relative border-l-2 border-[#704bfd] py-7 pl-7 sm:pl-10"><p className="text-[8px] font-black uppercase tracking-[.13em] text-[#704bfd]">Kamu bilang</p><blockquote className="mt-3 max-w-2xl text-3xl font-black leading-tight tracking-[-.04em] sm:text-4xl">“Cariin sepatu putih buat kuliah, empuk, budget 300 ribuan.”</blockquote><div className="mt-8 border-t border-[#dcdce0] pt-6"><p className="text-[8px] font-black uppercase tracking-[.13em] text-[#704bfd]">NEMU menangkap</p><p className="mt-2 text-sm font-bold text-[#3a3a42]">Sepatu putih · nyaman dipakai lama · gampang dibersihkan · maksimal Rp300 ribu</p></div></div></div></section>

    <section className="px-4 py-20 sm:px-6 lg:py-28" id="seller-pricing" aria-labelledby="pricing-heading"><div className="mx-auto max-w-[1240px]"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#704bfd]">Harga seller NEMU</p><h2 id="pricing-heading" className="mt-3 text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-5xl">Mulai dulu. Bayar setelah laku.</h2><p className="mt-5 text-sm leading-7 text-[#6b6b75]">Gratis sampai penjualan pertama. Setelah itu lanjut Rp199 ribu per bulan.</p><div className="mt-8 flex items-end gap-3 border-b-4 border-[#704bfd] pb-5"><strong className="text-6xl tracking-[-.07em]">Rp0</strong><span className="pb-2 text-[9px] font-black text-[#6b6b75]">sampai pecah telur</span></div><a className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#704bfd] px-6 py-4 text-[10px] font-black text-white" href="https://seller.nemu-ai.com/register">Buka toko gratis <ArrowRight size={15}/></a></div><div className="border-t border-[#dcdce0]">{[['Website toko','Langsung siap dibagi'],['AI marketing','Foto, konten, dan iklan'],['Mudah ditemukan','SEO dan AI search'],['Transaksi','DOKU dan 30+ kurir'],['Data jualan','Lihat omzet, untung, dan channel']].map(([title,copy],index)=><div className="grid grid-cols-[42px_1fr_1fr] gap-4 border-b border-[#dcdce0] py-5" key={title}><span className="text-[9px] font-black text-[#704bfd]">0{index+1}</span><b className="text-[10px]">{title}</b><span className="text-[9px] text-[#6b6b75]">{copy}</span></div>)}</div></div></div></section>

    <PaymentMethods />

    <section className="bg-[#704bfd] py-16 text-white" id="download-app" aria-labelledby="download-heading"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#e7dfff]">NEMU di genggaman</p><h2 id="download-heading" className="mt-3 text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-5xl">Belanja dan urus toko dari HP.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/75">Cari barang, cek pesanan, atau lanjut jualan kapan saja lewat aplikasi NEMU.</p></div><div className="flex flex-wrap gap-3"><a className="inline-flex min-w-[190px] items-center gap-3 rounded-2xl bg-[#1a1a1f] px-5 py-3 text-white shadow-[0_12px_24px_rgba(32,20,78,.22)] transition hover:-translate-y-1" href="https://apps.apple.com/id/app/nemu-ai-marketplace/id6789514376"><Apple className="shrink-0 text-white" size={28}/><span className="text-white"><small className="block text-[7px] font-bold text-white/65">Download di</small><b className="block text-sm text-white">App Store</b></span></a><a className="inline-flex min-w-[190px] items-center gap-3 rounded-2xl bg-[#1a1a1f] px-5 py-3 text-white shadow-[0_12px_24px_rgba(32,20,78,.22)] transition hover:-translate-y-1" href="https://play.google.com/store/apps/details?id=com.nemump.nemumobile&pcampaignid=web_share"><Play className="shrink-0 fill-white text-white" size={26}/><span className="text-white"><small className="block text-[7px] font-bold text-white/65">Download di</small><b className="block text-sm text-white">Google Play</b></span></a></div></div></section>

    <section className="bg-white px-4 py-20 sm:px-6 lg:py-28" aria-labelledby="faq-heading"><div className="mx-auto grid max-w-[1240px] gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#704bfd]">Yang sering ditanyain</p><h2 id="faq-heading" className="mt-3 text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-5xl">Biar makin jelas.</h2></div><div className="divide-y divide-[#dcdce0] border-y border-[#dcdce0]">{faq.map(([question,answer])=><details className="faq-item group" key={question}><summary className="flex cursor-pointer list-none items-center justify-between gap-5 py-5 text-[11px] font-black"><span>{question}</span><CirclePlus className="shrink-0 text-[#704bfd]" size={20}/></summary><p className="pb-5 pr-10 text-[10px] leading-6 text-[#6b6b75]">{answer}</p></details>)}</div></div></section>
    <Footer/>
  </main>;
}
