import { adChannels, calculateMarketingBudget, type MarketingBudget } from './marketing-budget';
import { rupiah } from './comparison-details';
import s from './calculator.module.css';
export default function MarketingBudgetEditor({ value, onChange }: { value: MarketingBudget; onChange: (next: MarketingBudget) => void }) {
  const result = calculateMarketingBudget(value);
  const input = (label: string, current: string, change: (v: string) => void, numeric = false) => <label className={s.field}><span>{label}</span><span className={s.inputWrap}><input type={numeric ? 'number' : 'text'} inputMode="numeric" min="0" step="1" value={current} placeholder="Isi budgetmu" onChange={e => change(e.target.value)} /></span></label>;
  return <div className={s.marketingEditor}>
    <div className={s.budgetBlock}><label className={s.check}><input type="checkbox" checked={value.socialEnabled} onChange={e => onChange({ ...value, socialEnabled: e.target.checked })} /><b>Kelola sosial media</b></label><p className={s.note}>Tentukan budget per video. Tim NEMU menyesuaikan penawaran dengan kebutuhanmu.</p>
      {value.socialEnabled && <><div className={s.twoCol}>{input('Jumlah video unik / bulan', value.videos, videos => onChange({ ...value, videos }), true)}{input('Budget seller per video (Rp)', value.perVideo, perVideo => onChange({ ...value, perVideo }))}</div><fieldset className={s.channelChoices}><legend>Kanal posting</legend>{['Instagram', 'TikTok', 'Facebook', 'YouTube Shorts'].map(channel => <label className={s.check} key={channel}><input type="checkbox" checked={value.postingChannels.includes(channel)} onChange={e => onChange({ ...value, postingChannels: e.target.checked ? [...value.postingChannels, channel] : value.postingChannels.filter(c => c !== channel) })} />{channel}</label>)}</fieldset><p className={s.note}>Jumlah video × budget per video. Satu video untuk beberapa kanal dihitung sekali. Ini budget pengajuan, bukan harga pasti; editing khusus dan posting perlu konfirmasi.</p></>}
    </div>
    <h3 className={s.platform}>Rencana iklan</h3><p className={s.note}>Iklan lewat NEMU adalah add-on layanan. Meta, TikTok, dan Google Ads yang kamu bayar langsung adalah pengeluaran usaha di luar NEMU, bukan admin atau potongan NEMU.</p>
    {adChannels.map(channel => { const ad = value.ads[channel.id]; const update = (patch: Partial<typeof ad>) => onChange({ ...value, ads: { ...value.ads, [channel.id]: { ...ad, ...patch } } }); return <div className={s.budgetBlock} key={channel.id}><label className={s.check}><input type="checkbox" checked={ad.enabled} onChange={e => update({ enabled: e.target.checked })} /><b>{channel.name}</b></label>{channel.id === 'nemu' && <span className={s.budgetTag}>Mulai Rp49.000 · sesuai layanan</span>}{ad.enabled && <div className={s.twoCol}>{input(channel.id === 'nemu' ? 'Total pengajuan NEMU / bulan (Rp)' : `Budget harian ${channel.name} (Rp)`, ad.budget, budget => update({ budget }))}{channel.id !== 'nemu' && input(`Hari tayang ${channel.name} / bulan`, ad.days, days => update({ days }), true)}</div>}<details className={s.feeRules}><summary>Info budget {channel.name}</summary><p className={s.note}>{channel.note}</p></details></div>; })}
    <p className={s.note}>Untuk kampanye yang sama, pilih pengajuan NEMU atau budget kanal langsung—jangan keduanya. Tambahkan biaya pengelolaan atau pajak yang belum termasuk ke operasional. Total iklan adalah rencana budget, bukan prediksi biaya lelang atau hasil penjualan.</p>
    <div className={s.budgetTotals}><div><span>Produksi / kelola video</span><b>{result.valid ? rupiah(result.social) : 'Periksa input'}</b></div>{result.items.map(item => <div key={item.id}><span>{item.name}</span><b>{result.valid ? rupiah(item.total) : '—'}</b></div>)}<div><strong>Total promosi / bulan</strong><strong>{result.valid ? rupiah(result.total) : 'Belum lengkap'}</strong></div></div>
    {result.errors.map(error => <p className={s.error} role="status" key={error}>{error}</p>)}
    <details className={s.details}><summary>Rumus & sumber budget iklan</summary><p>Rencana iklan kanal = budget harian × hari tayang (1–31 hari per bulan). Google dapat membelanjakan lebih/kurang per hari; rata-rata harian tidak selalu merupakan batas keras. Forecast mengulangi rencana bulanan yang sama, bukan menjadwalkan kampanye.</p><p><a href="https://ads.tiktok.com/help/article/budget" target="_blank" rel="noreferrer">Ketentuan budget TikTok Ads</a> · <a href="https://support.google.com/google-ads/answer/10486536?hl=en" target="_blank" rel="noreferrer">Cara kerja budget Google Ads</a> · <a href="https://support.google.com/google-ads/answer/16041302?hl=en" target="_blank" rel="noreferrer">YouTube Shorts Ads</a></p><p>Dicek 5 September 2026. Minimum Meta per akun belum terverifikasi. Rp49.000 berasal dari data layanan NEMU yang kamu berikan; bukan angka minimum platform iklan. Collab posting tetap melalui kurasi dan belum diberi harga.</p></details>
  </div>;
}
