'use client';

import { useState } from 'react';
import { planPrice, forecast, liveCapacity, parseRupiah } from './pricing';
import { livePlans, type Costs } from './calculation';
import s from './calculator.module.css';
import SkincareBenchmark from './skincare-benchmark';
import MarketingBudgetEditor from './marketing-budget-editor';
import { initialMarketingBudget, calculateMarketingBudget, type MarketingBudget } from './marketing-budget';
import { splitNemuCosts, nemuCostTotals, type NemuCostSplit } from './nemu-costs';
import PricingExpenseSummary from './pricing-expense-summary';
import PricingPromoGuide from './pricing-promo-guide';

const money = (n: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n);
const defaults = { product: '', packaging: '0', labor: '0', inbound: '0', shipping: '0', promo: '0', monthly: '0', liveHours: '0', units: '100', margin: '20' };
type Values = typeof defaults;
export default function PricingWorkbench({ onCompare }: { onCompare: (price: number, cost: number, orders: number, fees: Costs, split: NemuCostSplit, marketing: MarketingBudget) => void }) {
  const [values, setValues] = useState<Values>(defaults);
  const [months, setMonths] = useState(3);
  const [category, setCategory] = useState('serum');
  const [live, setLive] = useState<keyof typeof livePlans>('none');
  const [term, setTerm] = useState<1 | 6 | 12>(1);
  const [coreCharged, setCoreCharged] = useState(true);
  const [marketing, setMarketing] = useState(initialMarketingBudget);
  const marketingTotal = calculateMarketingBudget(marketing);
  const numeric = (key: keyof Values) => ['units', 'margin', 'percent', 'liveHours'].includes(key) ? Number(values[key]) : parseRupiah(values[key]);
  const optionalAmount = (key: keyof Values) => values[key].trim() !== '' && Number.isFinite(numeric(key)) && numeric(key) >= 0 && numeric(key) <= 1000000000 ? numeric(key) : null;
  const targetOrders = values.units.trim() !== '' && Number.isInteger(numeric('units')) && numeric('units') >= 0 && numeric('units') <= 1000000 ? numeric('units') : null;
  const capacity = values.liveHours.trim() !== '' && Number.isFinite(Number(values.liveHours)) && Number(values.liveHours) >= 0 && Number(values.liveHours) <= 744 ? liveCapacity(live, term, Number(values.liveHours)) : null;
  const valid = Object.entries(values).every(([key, value]) => value.trim() !== '' && Number.isFinite(numeric(key as keyof Values)) && numeric(key as keyof Values) >= 0 && numeric(key as keyof Values) <= (key === 'margin' || key === 'percent' ? 100 : key === 'liveHours' ? 744 : key === 'units' ? 1000000 : 1000000000)) && Number.isInteger(Number(values.units)) && Number(values.margin) < 100;
  const cost = numeric('product') + numeric('packaging') + numeric('labor') + numeric('inbound');
  const split = splitNemuCosts(coreCharged, live, term, numeric('monthly'), marketingTotal);
  const monthlyTotals = nemuCostTotals(split);
  const fees: Costs = { percent: 0, perOrder: 0, shipping: numeric('shipping'), promotion: numeric('promo'), monthly: monthlyTotals.monthly };
  const plan = valid && marketingTotal.valid ? planPrice({ cost, orders: Number(values.units), margin: Number(values.margin), fees }) : null;
  const result = plan && !('error' in plan) ? plan : null;
  const scenarios = result ? forecast(result.recommended, cost, Number(values.units), fees, months) : [];
  function field(key: keyof Values, label: string, unit = 'Rp') {
    const max = key === 'margin' ? 100 : key === 'liveHours' ? 744 : key === 'units' ? 1000000 : 1000000000;
    const n = numeric(key);
    const invalid = values[key] !== '' && (!Number.isFinite(n) || n < 0 || n > max || (key === 'units' && !Number.isInteger(n)) || (key === 'margin' && n === 100));
    return <label className={s.field}><span>{label}</span><span className={s.inputWrap}><small>{unit}</small><input type={unit === 'Rp' ? 'text' : 'number'} inputMode={unit === 'Rp' ? 'numeric' : 'decimal'} min="0" max={max} step={key === 'units' ? '1' : 'any'} value={values[key]} placeholder="Isi angka" aria-invalid={invalid} onChange={e => setValues({ ...values, [key]: e.target.value })} /></span>{invalid && <small className={s.error}>Isi angka 0–{max.toLocaleString('id-ID')}{key === 'units' || unit === 'Rp' ? ' tanpa desimal' : key === 'margin' ? ' (kurang dari 100)' : ''}.</small>}</label>;
  }
  return <div className={s.layout}>
    <div className={s.formColumn}>
      <details className={`${s.card} ${s.planDisclosure}`}><summary>Referensi harga skincare <span>Lihat kategori</span></summary><SkincareBenchmark category={category} onCategory={setCategory} suggested={result?.recommended} /></details>
      <section className={s.card} aria-labelledby="start-price-title"><div className={s.cardHeading}><span className={s.step}>01</span><h2 id="start-price-title">Mulai dari modalmu</h2></div><p>Belum punya harga jual? Rincikan biaya untuk satu produk.</p><div className={s.twoCol}>{field('product', 'Beli / produksi produk')}{field('packaging', 'Kemasan per produk')}{field('labor', 'Tenaga kerja per produk')}{field('inbound', 'Ongkir bahan per produk')}</div><p className={s.note}>Jangan masukkan biaya yang sama dua kali. Jika tenaga kerja atau ongkir sudah masuk harga produksi, isi 0 pada rinciannya. Nominal boleh ditulis 150000 atau 150.000 (rupiah utuh).</p><div className={s.miniResult}><span>Total modal per produk</span><b>{['product', 'packaging', 'labor', 'inbound'].every(k => Number.isFinite(numeric(k as keyof Values)) && numeric(k as keyof Values) >= 0 && numeric(k as keyof Values) <= 1000000000) ? money(cost) : '—'}</b></div></section>
      <section className={s.card} aria-labelledby="pricing-fees-title"><div className={s.cardHeading}><span className={s.step}>02</span><h2 id="pricing-fees-title">Langganan & biaya toko</h2></div><label className={s.check}><input type="checkbox" checked={coreCharged} onChange={e => setCoreCharged(e.target.checked)} />Hitung Core Rp199.000 / bulan</label><p className={s.note}>Tanpa komisi penjualan NEMU. Nonaktifkan Core jika belum ditagih. Add-on iklan, video, dan Live dipilih terpisah.</p><details className={s.disclosure}><summary>Operasional, ongkir & promo seller <span>Opsional</span></summary>{field('monthly', 'Host, sewa & operasional lain / bulan')}<div className={s.twoCol}>{field('shipping', 'Subsidi ongkir rata-rata / pesanan')}{field('promo', 'Promo seller / pesanan')}</div><p className={s.note}>Bukan komisi NEMU. Isi rata-rata subsidi, bukan batas maksimal. Jangan hitung diskon, Core, atau add-on yang sudah dimasukkan dua kali.</p></details></section>
      <section className={s.card} aria-labelledby="growth-title">
        <div className={s.cardHeading}><span className={s.step}>03</span><h2 id="growth-title">Rencana promosi & Live</h2></div>
        <MarketingBudgetEditor value={marketing} onChange={setMarketing} />
        <details className={s.disclosure}><summary>Tambahkan Live <span>{livePlans[live].name} · {money(livePlans[live].prices[term])} / bulan</span></summary><div className={s.twoCol}><label className={s.field}><span>Paket Live untuk forecast</span><select value={live} onChange={e => setLive(e.target.value as keyof typeof livePlans)}>{Object.entries(livePlans).map(([key, value]) => <option key={key} value={key}>{value.name}</option>)}</select></label><label className={s.field}><span>Kontrak Live</span><select value={term} onChange={e => setTerm(Number(e.target.value) as 1 | 6 | 12)}>{[1, 6, 12].map(n => <option key={n} value={n}>{n} bulan</option>)}</select></label>{field('liveHours', 'Target Live per bulan', 'jam')}</div>
        {capacity && <><div className={s.miniResult}><span>Kuota paket {capacity.includedHours} jam/bulan · {capacity.totalHours} jam / {term} bulan</span><b>{money(capacity.monthly)} / bulan</b><span>Targetmu: {capacity.targetTotal} jam selama {term} bulan</span></div>{capacity.missingHours > 0 && <p className={s.notice} role="status">Target melebihi kuota {capacity.missingHours} jam/bulan. Minta penawaran tambahan dari NEMU; biaya jam tambahan belum dihitung. Harga dan forecast ini belum menutup seluruh rencana Live.</p>}</>}
        <p className={s.note}>Harga Live beta dari referensi internal; konfirmasi sebelum berlangganan. Human/AI: 10 jam per bulan. Hybrid: 10 jam Human + 10 jam AI, tidak saling menggantikan. Core diasumsikan di luar paket Live. Host manusia diisi pada operasional. Forecast mempertahankan tarif bulanan ini, termasuk setelah masa kontrak; harga perpanjangan belum pasti. Jam Live tidak otomatis menjadi pesanan.</p>
        </details><p className={s.note}>Iklan lewat NEMU termasuk add-on NEMU. Iklan mandiri di Meta, TikTok, atau YouTube masuk pengeluaran usaha di luar NEMU. Semuanya masuk harga saran dan forecast sesuai budget yang diisi, tanpa dihitung dua kali.</p>
      </section>
      <section className={s.card} aria-labelledby="target-title"><div className={s.cardHeading}><span className={s.step}>04</span><h2 id="target-title">Tentukan targetmu</h2></div><div className={s.twoCol}>{field('units', 'Target pesanan per bulan', '×')}{field('margin', 'Target sisa dari omzet', '%')}</div><p className={s.note}>Margin dihitung setelah modal dan biaya yang kamu isi, bukan markup atas modal. Satu pesanan = satu produk. Target pesanan adalah asumsi yang kamu tentukan, bukan perkiraan dari data pasar.</p><PricingExpenseSummary totals={monthlyTotals} split={split} orders={targetOrders} shipping={optionalAmount('shipping')} promotion={optionalAmount('promo')} marketing={marketingTotal} operations={optionalAmount('monthly')} /></section>
    </div>
    <aside className={s.formColumn} aria-label="Harga dan forecast NEMU">
      <section className={s.summary} aria-live="polite"><span className={s.eyebrow}>HARGA JUAL SARAN · NEMU</span><h2>{result ? 'Mulai uji di harga ini.' : 'Lengkapi rencana jualanmu.'}</h2>{result ? <><strong className={s.bigNumber}>{money(result.recommended)}</strong><p>Dibulatkan ke atas per Rp100. Target margin tercapai hanya jika asumsi biaya dan pesanan terpenuhi.</p><div className={s.summaryStrip}><span>Harga impas pada target pesanan</span><b>{money(result.floor)}</b></div><div className={s.summaryStrip}><span>Titik impas / bulan pada harga saran</span><b>{result.breakEvenOrders === null ? 'Tidak tercapai' : `${result.breakEvenOrders} pesanan`}</b></div><div className={s.summaryStrip}><span>Sisa / bulan pada target</span><b>{money(result.result.remainder)}</b></div><p>Margin simulasi {result.actualMargin.toFixed(1)}%. Sisa ini belum termasuk pajak, retur, atau biaya lain yang tidak diisi.</p></> : <p role="status">{plan && 'error' in plan ? plan.error : marketingTotal.errors[0] ?? 'Isi modal produk dan target pesanan. Pilih hanya add-on yang kamu perlukan.'}</p>}</section>
      {result && <>
        <PricingPromoGuide key={category} category={category} recommended={result.recommended} input={{ cost, orders: Number(values.units), margin: Number(values.margin), fees }} ads={marketingTotal.ads} onPromotion={promo => setValues(previous => ({ ...previous, promo: String(promo) }))} />
        <section className={s.card} aria-labelledby="forecast-title"><div className={s.cardHeading}><h2 id="forecast-title">Kalau jualannya segini?</h2></div><label className={s.field}><span>Periode forecast</span><select value={months} onChange={e => setMonths(Number(e.target.value))}>{[1, 3, 6, 12].map(n => <option key={n} value={n}>{n} bulan</option>)}</select></label><div className={s.tableScroll}><table><caption>Proyeksi {months} bulan pada harga {money(result.recommended)}</caption><thead><tr><th>Skenario</th><th>Pesanan / bln</th><th>Omzet total</th><th>Sisa total</th></tr></thead><tbody>{scenarios.map(row => <tr key={row.name}><th scope="row">{row.name}<br /><small>{row.multiplier * 100}% target</small></th><td>{row.orders}</td><td>{money(row.revenue)}</td><td>{money(row.remainder)}</td></tr>)}</tbody></table></div><p className={s.note}>Volume tetap setiap bulan: 50%, 100%, dan 150% target, dibulatkan ke bawah ke pesanan utuh. Harga dan biaya tetap; biaya bulanan dibebankan setiap bulan. Ini simulasi skenario, bukan prediksi AI atau jaminan penjualan.</p></section>
        <section className={s.card} aria-labelledby="suggestion-title"><div className={s.cardHeading}><h2 id="suggestion-title">Langkah yang bisa kamu coba</h2></div><span className={s.beta}>SARAN BERBASIS PERHITUNGAN</span><ul className={s.advice}>
          {capacity && capacity.missingHours > 0 && <li><b>Lengkapi anggaran Live dulu.</b> Ada {capacity.missingHours} jam/bulan di luar kuota. Harga saran belum memasukkan biaya tambahan itu; konfirmasi ke NEMU sebelum memakai hasil ini.</li>}
          <li><b>Uji harga {money(result.recommended)}.</b> Bandingkan dengan produk sejenis dan respons pembeli. Jika terlalu tinggi, tinjau modal atau target margin; jangan langsung memangkas harga di bawah {money(result.floor)} pada target volume ini.</li>
          <li>{scenarios[0].monthlyRemainder < 0 ? <>Skenario sepi masih minus <b>{money(Math.abs(scenarios[0].monthlyRemainder))}/bulan</b>. Tinjau biaya bulanan dan siapkan cadangan biaya sebelum menambah pengeluaran.</> : <>Skenario sepi menyisakan <b>{money(scenarios[0].monthlyRemainder)}/bulan</b> sebelum biaya yang belum dimasukkan. Cek lagi asumsi ongkir, promo, dan retur.</>}</li>
          <li>{result.breakEvenOrders === null ? 'Kontribusi per pesanan belum cukup untuk menutup biaya.' : <>Butuh minimal <b>{result.breakEvenOrders} pesanan/bulan</b> untuk menutup biaya yang diisi pada harga saran. Perbarui simulasi dengan pesanan aktual, bukan target saja.</>}</li>
        </ul><details className={s.details}><summary>Lihat cara menghitung</summary><p>Harga = (modal, ongkir, dan promo per pesanan + total langganan, add-on, dan operasional bulanan ÷ target pesanan) ÷ (1 − margin%). Tidak ada persentase komisi NEMU. Titik impas = biaya bulanan ÷ kontribusi per pesanan, dibulatkan ke atas.</p></details><p className={s.note}>Saran otomatis dari rumus lokal, tidak memakai API Codex atau mengirim data ke AI. Belum menghitung pertumbuhan, stok, atau arus kas.</p><button className={s.primary} disabled={result.recommended > 1000000000 || cost > 1000000000 || fees.monthly > 1000000000} onClick={() => onCompare(result.recommended, cost, Number(values.units), fees, split, marketing)}>Pakai untuk bandingkan marketplace →</button>{(result.recommended > 1000000000 || cost > 1000000000 || fees.monthly > 1000000000) && <p className={s.error}>Belum bisa dipindahkan: mode perbandingan membatasi harga, modal, dan biaya bulanan masing-masing Rp1 miliar.</p>}<p className={s.note}>Angka dipindahkan dengan Core, Live, add-on NEMU, dan pengeluaran usaha tetap terpisah. Tidak dihitung ulang dua kali. Tarif pembanding tetap perlu diisi.</p></section>
      </>}
    </aside>
  </div>;
}
