import type { Metadata } from 'next';
import { ArrowRight, BadgeCheck, ChevronRight, Dumbbell, Headphones, House, MessageCircleMore, Palette, Recycle, RotateCcw, ShieldCheck, Shirt, ShoppingBag, Smartphone, Sparkles, Star, Store, Truck, Zap } from 'lucide-react';
import { Footer, Header } from '../components';
import { CategoryFilter, FavoriteButton, ShopSearch } from './shop-client';

export const metadata: Metadata = { title:'Belanja — NEMU AI', description:'Tulis barang yang kamu butuhkan. NEMU menyaring produk lokal dan preloved yang paling cocok.' };

const cats = [
  {icon:Shirt,name:'Fashion',color:'bg-rose-50 text-rose-600'}, {icon:Smartphone,name:'HP & Gadget',color:'bg-sky-50 text-sky-600'}, {icon:Sparkles,name:'Kecantikan',color:'bg-pink-50 text-pink-600'}, {icon:House,name:'Rumah',color:'bg-amber-50 text-amber-600'}, {icon:Headphones,name:'Elektronik',color:'bg-violet-50 text-violet-600'}, {icon:Dumbbell,name:'Olahraga',color:'bg-emerald-50 text-emerald-600'}, {icon:Palette,name:'Hobi',color:'bg-orange-50 text-orange-600'}, {icon:Recycle,name:'Preloved',color:'bg-lime-50 text-lime-700'}, {icon:ShoppingBag,name:'Semua',color:'bg-zinc-100 text-zinc-700'},
];

const products = [
  {name:'Vivo V11 Pro 6/64',price:'Rp950.000',old:'Rp1.050.000',badge:'-10%',note:'Preloved · Bagus',city:'Klaten',img:'https://s3.ap-southeast-3.amazonaws.com/s3-production-nemu-ai/products/7008540f-9a9c-4917-9368-55b0e5335908.png'},
  {name:'GM Shoes Flat Sandal',price:'Rp70.000',old:'',badge:'Lokal',note:'Baru',city:'Jakarta',img:'https://s3.ap-southeast-3.amazonaws.com/s3-production-nemu-ai/products/b65c53f0-b789-4dd0-84a0-ba883188e12a.jpg'},
  {name:'Kopi Gayo Arabika 250gr',price:'Rp95.000',old:'Rp110.000',badge:'-14%',note:'Best seller',city:'Aceh',img:'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=700&auto=format&fit=crop&q=80'},
  {name:'Arunika Work Tote',price:'Rp749.000',old:'',badge:'96% cocok',note:'Kulit asli',city:'Bandung',img:'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=700&auto=format&fit=crop&q=80'},
  {name:'Keramik Mug Handmade',price:'Rp180.000',old:'',badge:'Lokal',note:'Buatan tangan',city:'Bandung',img:'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=700&auto=format&fit=crop&q=80'},
  {name:'Aluna Linen Dress',price:'Rp385.000',old:'Rp429.000',badge:'-10%',note:'4 warna',city:'Yogyakarta',img:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=700&auto=format&fit=crop&q=80'},
  {name:'Kacamata Acetate',price:'Rp420.000',old:'',badge:'Official',note:'Unisex',city:'Bandung',img:'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=700&auto=format&fit=crop&q=80'},
  {name:'Tenun Sumba Laras',price:'Rp650.000',old:'',badge:'Lokal',note:'Buatan tangan',city:'NTT',img:'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=700&auto=format&fit=crop&q=80'},
  {name:'Vivo Y12s 3/32',price:'Rp750.000',old:'Rp850.000',badge:'-12%',note:'Preloved · Bagus',city:'Klaten',img:'https://s3.ap-southeast-3.amazonaws.com/s3-production-nemu-ai/products/5b7d6a77-a594-420a-907c-edeafcdab0c4.png'},
  {name:'Jam Tangan Minimal',price:'Rp1.250.000',old:'',badge:'Official',note:'Garansi toko',city:'Jakarta',img:'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=700&auto=format&fit=crop&q=80'},
];

const stores = [
  {name:'AREI',category:'Outdoor & travel',initial:'AR',tone:'bg-emerald-700'}, {name:'TRACKER',category:'Sepatu & sandal',initial:'TR',tone:'bg-violet-700'}, {name:'Cartenz',category:'Gear pendakian',initial:'CA',tone:'bg-orange-500'}, {name:'KRIYA.',category:'Barang lokal pilihan',initial:'KR',tone:'bg-zinc-900'},
];

export default function ShopPage() {
  return (
    <main className="bg-zinc-100 text-zinc-950">
      <Header />

      <section className="mx-auto grid max-w-[1180px] gap-3 px-4 py-5 sm:px-6 lg:grid-cols-[2fr_1fr] lg:grid-rows-2">
        <article className="relative overflow-hidden rounded-3xl bg-violet-600 p-7 text-white lg:row-span-2 lg:min-h-[365px] lg:p-11"><div className="relative z-10 max-w-xl"><span className="inline-flex items-center gap-1.5 rounded-full bg-lime-300 px-3 py-1.5 text-[8px] font-black uppercase tracking-widest text-zinc-950"><Sparkles size={12}/> Pencarian dengan AI</span><h1 className="mt-5 font-[var(--font-display)] text-5xl font-black leading-[.88] tracking-[-.065em] sm:text-7xl">Tulis kebutuhannya.<br/><span className="text-lime-300">Kami cari barangnya.</span></h1><p className="mt-5 max-w-md text-xs leading-5 text-violet-100">Budget, warna, kondisi, sampai lokasi—tulis sekali. NEMU menyaring pilihan yang paling cocok.</p><a className="mt-6 inline-flex items-center gap-3 rounded-xl bg-white px-4 py-3 text-[9px] font-black text-violet-800" href="#tanya-nemu">Cariin barang saya <ArrowRight size={15}/></a></div><div className="absolute -bottom-24 -right-20 size-80 rounded-full bg-lime-300/90"/><div className="absolute bottom-8 right-7 hidden w-64 rotate-2 rounded-2xl bg-white p-5 text-zinc-950 shadow-2xl sm:block"><Sparkles size={20} className="text-violet-600"/><p className="mt-3 text-xs font-semibold leading-5">“Cari kado untuk ibu, budget Rp200 ribu.”</p><div className="mt-4 flex items-center justify-between border-t border-zinc-100 pt-3"><b className="text-[9px] text-violet-700">38 pilihan sudah disaring</b><ChevronRight size={15}/></div></div></article>
        <article className="flex min-h-40 flex-col justify-between rounded-3xl bg-lime-300 p-6"><div className="flex items-center justify-between"><span className="rounded-full bg-zinc-950 px-3 py-1.5 text-[8px] font-black text-white">PESANAN PERTAMA</span><Truck size={22}/></div><div><h2 className="text-3xl font-black leading-[.95] tracking-[-.05em]">Belanja pertama.<br/>Ongkir kami bantu.</h2><p className="mt-2 text-[9px] font-bold">Gratis hingga Rp30 ribu</p></div></article>
        <article className="flex min-h-40 flex-col justify-between rounded-3xl bg-orange-500 p-6 text-white"><div className="flex items-center justify-between"><span className="rounded-full bg-white px-3 py-1.5 text-[8px] font-black text-orange-600">PRELOVED</span><Recycle size={22}/></div><div><h2 className="text-3xl font-black leading-[.95] tracking-[-.05em]">Kondisi bagus.<br/>Harga lebih ringan.</h2><p className="mt-2 flex items-center gap-1 text-[9px] font-bold">Lihat pilihan preloved <ChevronRight size={12}/></p></div></article>
      </section>

      <section className="mx-auto grid max-w-[1132px] gap-4 rounded-2xl border border-violet-200 bg-violet-100 p-4 lg:grid-cols-[230px_1fr] lg:items-center" id="tanya-nemu"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-violet-600 text-white"><MessageCircleMore size={18}/></span><div><b className="block text-xs">Tulis seperti lagi chat</b><small className="text-[8px] text-violet-700">Budget, warna, ukuran—sebutkan saja.</small></div></div><ShopSearch /></section>

      <section className="mx-auto mt-4 max-w-[1132px] rounded-2xl bg-white p-5 shadow-sm sm:p-7" id="kategori"><div className="flex items-end justify-between"><h2 className="text-2xl font-black tracking-[-.04em]">Pilih kategorinya. Lihat barangnya.</h2><a className="flex items-center gap-1 text-[9px] font-extrabold text-violet-700" href="#produk">Semua kategori <ChevronRight size={13}/></a></div><div className="mt-7 flex gap-4 overflow-x-auto pb-2 [scrollbar-width:none] lg:grid lg:grid-cols-9">{cats.map(({icon:Icon,name,color})=><a className="flex min-w-20 flex-col items-center gap-2 text-center" href="#produk" key={name}><span className={`grid size-16 place-items-center rounded-full transition hover:-translate-y-1 ${color}`}><Icon size={25}/></span><b className="text-[8px] font-bold">{name}</b></a>)}</div></section>

      <section className="mx-auto mt-4 max-w-[1132px] rounded-2xl bg-white p-5 shadow-sm sm:p-7"><div className="flex items-end justify-between"><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-orange-100 text-orange-600"><Zap size={18} fill="currentColor"/></span><div><h2 className="text-2xl font-black tracking-[-.04em]">Harga turun. Stok jalan.</h2><span className="mt-1 inline-block rounded-md bg-violet-600 px-2 py-1 text-[8px] font-black tracking-wider text-white">01 : 42 : 18</span></div></div><a className="hidden items-center gap-1 text-[9px] font-extrabold text-violet-700 sm:flex" href="#produk">Lihat semua <ChevronRight size={13}/></a></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{products.slice(0,5).map((p,index)=><article className={`${index>1?'hidden sm:block':''} ${index>2?'sm:hidden lg:block':''}`} key={p.name}><div className="relative aspect-square overflow-hidden rounded-xl bg-zinc-100"><img className="size-full object-cover transition duration-300 hover:scale-105" src={p.img} alt={p.name}/><span className="absolute left-2 top-2 rounded-md bg-orange-500 px-2 py-1 text-[7px] font-black text-white">{p.badge}</span></div><p className="mt-2 line-clamp-2 min-h-8 text-[9px] font-semibold leading-4">{p.name}</p><strong className="block text-xs text-violet-700">{p.price}</strong>{p.old&&<del className="text-[7px] text-zinc-400">{p.old}</del>}<div className="mt-2 h-4 overflow-hidden rounded-full bg-zinc-200"><div className="h-full rounded-full bg-orange-400" style={{width:`${[72,84,63,91,77][index]}%`}}/><span className="relative -top-[13px] block text-center text-[6px] font-bold text-white">Stok terbatas</span></div></article>)}</div></section>

      <section className="mx-auto max-w-[1132px] px-1 py-14"><div className="flex items-end justify-between"><div><span className="text-[8px] font-black uppercase tracking-[.14em] text-violet-700">Toko terverifikasi</span><h2 className="mt-1 text-3xl font-black tracking-[-.05em]">Toko resmi. Sudah kami cek.</h2></div><a className="hidden items-center gap-1 text-[9px] font-extrabold text-violet-700 sm:flex" href="https://shop.nemu-ai.com/toko">Semua toko <ChevronRight size={13}/></a></div><div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{stores.map(store=><article className="relative overflow-hidden rounded-2xl border border-zinc-200 bg-white p-5 transition hover:-translate-y-1 hover:shadow-xl hover:shadow-zinc-950/5" key={store.name}><div className={`grid size-12 place-items-center rounded-2xl text-sm font-black text-white ${store.tone}`}>{store.initial}</div><span className="absolute right-4 top-4 flex items-center gap-1 rounded-full bg-green-50 px-2 py-1 text-[7px] font-black text-green-700"><BadgeCheck size={11}/> Official</span><b className="mt-8 block text-lg font-black tracking-tight">{store.name}</b><p className="mt-1 text-[8px] text-zinc-500">{store.category}</p></article>)}</div></section>

      <section className="mx-auto max-w-[1132px] pb-16" id="produk"><div><span className="text-[8px] font-black uppercase tracking-[.14em] text-violet-700">Dipilih untuk kamu</span><h2 className="mt-1 text-3xl font-black tracking-[-.05em]">Pilihan relevan. Bukan asal lewat.</h2></div><div className="mt-6"><CategoryFilter categories={['Semua','Paling dicari','Di bawah Rp200 ribu','Brand lokal','Preloved']}/></div><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{products.map(p=><article className="group overflow-hidden rounded-2xl border border-zinc-200 bg-white transition hover:-translate-y-1 hover:border-violet-200 hover:shadow-xl hover:shadow-violet-950/5" key={p.name}><div className="relative aspect-square overflow-hidden bg-zinc-100"><img className="size-full object-cover transition duration-300 group-hover:scale-105" src={p.img} alt={p.name}/><span className="absolute left-2 top-2 rounded-md bg-violet-600 px-2 py-1 text-[7px] font-black text-white">{p.badge}</span><FavoriteButton name={p.name}/></div><div className="p-3"><h3 className="line-clamp-2 min-h-8 text-[10px] font-bold leading-4">{p.name}</h3><p className="mt-1 text-[7px] text-zinc-400">{p.note}</p><div className="mt-2"><strong className="text-xs text-violet-700">{p.price}</strong>{p.old&&<del className="ml-2 text-[7px] text-zinc-400">{p.old}</del>}</div><small className="mt-3 flex items-center gap-1 text-[7px] text-zinc-400"><Star size={10} fill="#facc15" className="text-yellow-400"/> 4.9 · {p.city}</small></div></article>)}</div><button className="mx-auto mt-8 flex items-center gap-2 rounded-xl border border-violet-300 bg-white px-6 py-3 text-[9px] font-black text-violet-700 transition hover:bg-violet-50">Tampilkan produk lainnya <ChevronRight size={14}/></button></section>

      <section className="border-y border-zinc-200 bg-white px-4 py-8 sm:px-6"><div className="mx-auto grid max-w-[1132px] grid-cols-2 gap-6 lg:grid-cols-4">{[[ShieldCheck,'Pembayaran terlindungi','Dana diteruskan setelah barang sampai.'],[BadgeCheck,'Seller diverifikasi','Identitas dan status toko terlihat jelas.'],[RotateCcw,'Komplain tersedia','Laporkan masalah langsung dari pesanan.'],[Sparkles,'AI membantu menyaring','Rekomendasi mengikuti kebutuhanmu.']].map(([Icon,title,copy])=>{const I=Icon as typeof ShieldCheck;return <div className="flex gap-3" key={title as string}><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-violet-100 text-violet-700"><I size={18}/></span><div><b className="block text-[9px]">{title as string}</b><p className="mt-1 text-[7px] leading-4 text-zinc-400">{copy as string}</p></div></div>})}</div></section>

      <section className="bg-violet-950 px-4 py-20 text-white sm:px-6"><div className="mx-auto grid max-w-[1132px] items-end gap-10 lg:grid-cols-[1fr_.7fr]"><div><span className="flex items-center gap-2 text-[8px] font-black uppercase tracking-[.14em] text-lime-300"><Store size={13}/> Jualan di NEMU</span><h2 className="mt-3 font-[var(--font-display)] text-5xl font-black leading-[.9] tracking-[-.06em] sm:text-6xl">Upload barang.<br/>Listing langsung jadi.</h2></div><div><p className="text-xs leading-6 text-violet-200">AI membantu menulis judul, deskripsi, dan kategori. Kamu fokus mengatur harga dan melayani pembeli.</p><a className="mt-5 inline-flex items-center gap-3 rounded-xl bg-lime-300 px-5 py-4 text-[9px] font-black text-zinc-950" href="https://seller.nemu-ai.com/register">Buka toko saya <ArrowRight size={15}/></a></div></div></section>
      <Footer />
    </main>
  );
}
